repos:
- repo: https://github.com/sirwart/ripsecrets
  rev: v0.1.7  # Use latest tag on GitHub
  hooks:
  - id: ripsecrets
    args:
    # OpenAI keys
    - --additional-pattern
    - '(?:sk-)[0-9a-zA-Z_-]{48}'
    # generic [...]_API_KEY=[...] pattern
    - --additional-pattern
    - '_API_KEY=[0-9a-zA-Z_-]{10}'
    # generic [...]_PASSWORD=[...] pattern
    - --additional-pattern
    - '_PASSWORD=[0-9a-zA-Z_-]{10}'
- repo: https://github.com/psf/black
  rev: 25.12.0  # Use latest tag on GitHub
  hooks:
  - id: black-jupyter
